pull_request_rules:
   - name: automatic merge for Dependabot pull requests
     conditions:
       - author~=^dependabot(|-preview)\[bot\]$
       - status-success=Amazon ECR Private
       - status-success=Amazon ECR Public
       - status-success=Local build
       - status-success=Python tests
       - status-success=Dockerfile linter
       - status-success=Local build
       - base=main
     actions:
       merge:
         method: squash
